version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    executor: ruby_2_6
    steps:
      - checkout
      - run:
          name: Update bundler
          command: |
            sudo gem update --system
            gem uninstall bundler
            sudo rm /usr/local/bin/bundler
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Configure bundler path
          command: bundle config path vendor/bundle
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1
      - run:
          name: Install dependencies
          command: bundle install --jobs=2 --retry=2
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Specs
          command: bundle exec rspec

executors:
  ruby_2_6:
    docker:
      - image: circleci/ruby:2.6
