name: verification

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libsqlite3
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
      - name: Setup ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop
      - name: Specs
        run: bundle exec rspec
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      HEROKU_BASE_URL: "https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com"
    steps:
      - uses: actions/checkout@v2
      - name: What is the github.ref?
        run: echo "${{ github.ref }}"
      - name: Repository information
        run: |
          cd $GITHUB_WORKSPACE && git remote -v && git branch -a
      - name: Unshallow the clone
        run: |
          cd $GITHUB_WORKSPACE && git fetch --unshallow origin
      - name: Push to heroku
        run: |
          cd $GITHUB_WORKSPACE && git push -f $HEROKU_URL $GIT_SOURCE_REF:master
        env:
          HEROKU_URL: "${{ env.HEROKU_BASE_URL }}/${{ secrets.HEROKU_APP_NAME }}.git"
          GIT_SOURCE_REF: "${{ github.ref }}"
